# Generated by Django 5.0.4 on 2025-09-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_block', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='certificates/')),
                ('qr_code', models.ImageField(upload_to='qr/')),
                ('ipfs_cid', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_hash', models.CharField(max_length=255, unique=True)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('issued_block', models.IntegerField(blank=True, default=None, null=True)),
                ('revoked_block', models.IntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_no', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevokedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revocation', to='core.certificate')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.student'),
        ),
    ]
